spring.application.name=kafka-spring
server.port=8080

spring.cloud.stream.bindings.pageEventConsumer-in-0.destination=Publishing
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=Supplying

spring.cloud.stream.bindings.kStreamFunction-in-0.destination=Supplying
spring.cloud.stream.bindings.kStreamFunction-out-0.destination=Streaming

spring.cloud.stream.bindings.pageEventSupplier-out-0.producer.poller.fixed-delay=200
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=5000

spring.cloud.function.definition=pageEventConsumer;pageEventSupplier;kStreamFunction;